### ISSUE TITLE
Messages mapping on Transifex: missing messages to translate

### ISSUE THREAD

**Issue by thiagoeec** [w3c/epubcheck#924] opened 2018-12-08 15:51 UTC
Hi, everyone.

I've just finished translanting EPUBCheck to Brazilian Portuguese (pt-BR). Then, I bulk checked the ".\src\test" files (epub, opf, xhtml, and svg) for debugging purposes.

The result: there are several messages not extracted to Transifex. Check the [Error-list.txt](https://github.com/w3c/epubcheck/files/2659828/Error-list.txt) file for a list of those messages (at least the ones I could spot). Notice that part of the text may be already translated. I put the whole message to help finding them on the code.

Also, I've noticed a substitution item not correctly set:

Message:
`ERROR(RSC-005): ./test/resources/30/epub/invalid/lorem-xht-rng-1.epub/EPUB/lorem.xhtml(22,27): Erro ao processar o arquivo: elemento "epub:x" não permitido aqui; esperado a tag de fechamento do elemento, text ou elemento "a", "abbr", "area", "audio", "b", "bdi", "bdo", "br", "button", "canvas", "cite", "code", "command", "datalist", "del", "dfn", "em", "embed", "epub:switch", "i", "iframe", "img", "input", "ins", "kbd", "keygen", "label", "link", "map", "mark", "meta", "meter", "ns1:math", "ns2:svg", "object", "output", "progress", "q", "ruby", "s", "samp", "script", "select", "small", "span", "strong", "sub", "sup", "textarea", "time", "u", "var", "video" ou "wbr" (com xmlns:ns1="http://www.w3.org/1998/Math/MathML" xmlns:ns2="http://www.w3.org/2000/svg")`

The string '**text**' is being automaticaly filled, but it should be translated (text --> texto, in pt-BR).
There is a translation entry especific for this word in here:
`com/thaiopensource/relaxng/pattern/resources/Messages.properties`
Maybe, another instance os this entry should be present on other '.properties' files.

**Comment by tofi86** [comment] 2018-12-08 21:29
Hey Thiago,

this is most likely related to #474.
There are several messages thrown from Schematron checks where there is no localization concept present. This results in a generic localizable Java message part and a non-localizable schematron message part in the same EPUBCheck message.

Check this as an example from your txt file:
https://github.com/w3c/epubcheck/blob/master/src/main/resources/com/adobe/epubcheck/schema/30/multiple-renditions/container.sch#L17-L19

Regarding `RSC-005` I need to have a closer look in the next couple days. The message comes from the Jing parser, so the source is most likely a Jing issue. I'll see what we can do here...

**Comment by rdeltour** [comment] 2019-01-17 00:37
I had a look into this: the list of messages mentioned by @thiagoeec indeed correspond to the messages issued by Schematron, which are unfortunately not localized at this stage. This is tracked as #474.

As for the non-translation of `text`, I couldn't reproduce this: I got it translated correctly, testing both with French and Brazilian Portuguese locale.

**Comment by rdeltour** [comment] 2019-01-17 00:40
Closing and mark as `duplicate`, please refer to #474.

Feel free to reopen or keep on commenting, if the part about the `text` message still doesn't work after the Portuguese translation is integrated!

**Closed by rdeltour** 2019-01-17 00:40 UTC
Labels: type: duplicate
