### ISSUE TITLE
OpenCL error messages on OS X 

### ISSUE THREAD

**Issue by senki** [w3c/epubcheck#642] opened 2015-10-26 15:08 UTC
epubcheck 4.0 and 4.0.1 sometimes generates a series of error messages, even if the file is valid:

```
$ epubcheck issue169.epub
Validating using EPUB version 2.0.1 rules.
** OpenCL Error Notification: OpenCL Build Warning : Compiler build log:
warning: macro definitions used to build the precompiled header are missing
<built-in>:170:1: note: using this macro definition from precompiled header
#define cl_APPLE_fp64_basic_ops 1
^
<built-in>:169:1: note: using this macro definition from precompiled header
#define cl_khr_byte_addressable_store 1
^
<built-in>:164:1: note: using this macro definition from precompiled header
#define cl_khr_fp64 1
^
<built-in>:165:1: note: using this macro definition from precompiled header
#define cl_khr_global_int32_base_atomics 1
^
<built-in>:166:1: note: using this macro definition from precompiled header
#define cl_khr_global_int32_extended_atomics 1
^
<built-in>:167:1: note: using this macro definition from precompiled header
#define cl_khr_local_int32_base_atomics 1
^
<built-in>:168:1: note: using this macro definition from precompiled header
#define cl_khr_local_int32_extended_atomics 1
^

 **
No errors or warnings detected.
epubcheck completed
```

Above is tested with the `/src/test/resources/20/epub/valid/issue169.epub` file.
Not every file generates this error messages.
epubcheck 3.0.1 woks fine.

Mac OS X 10.11.1, java version "1.8.0_65"

**Comment by rdeltour** [comment] 2015-10-26 20:26
I cannot reproduce with Java 1.8.0_65 under OS X 10.10.5. 
Have you tried on another machine running OS X 10.11.1 or is it specific to your setup? I'll try to get my hands on an El Capitan box to try and reproduce here.

**Comment by tofi86** [comment] 2015-10-26 22:39
Is it possible that you installed EpubCheck via Homebrew? Does it also happen when running EpubCheck normally with `java -jar epubcheck.jar file.epub`?

**Comment by senki** [comment] 2015-11-06 19:43
Sorry for late reply, I missed the notification.

Yes, first I installed via homebrew, and later try to build myself. Every time I ran to this message.
Today I want to reproduce my problem, to try @tofi86's idea, and, fortunately,  I couldn't reproduce the above messages. 
In the meantime I completely remove and reinstall all homebrew packages, so something there is caused my problem.

P.S. when I try my builds, I always use the following bash script to start epubcheck:
```bash
#!/bin/bash
exec java  -jar ~/bin/epubcheck-bin/epubcheck.jar "$@"
```

**Comment by tofi86** [comment] 2015-11-06 23:16
> Today I want to reproduce my problem, to try @tofi86's idea, and, fortunately, I couldn't reproduce the above messages.
> In the meantime I completely remove and reinstall all homebrew packages, so something there is caused my problem.

Okay, so I think we can close this issue...
Feel free to post to this thread in case of further questions on the topic.

Last note: make sure you have the `lib/` folder placed in `~/bin/epubcheck-bin/` when running EpubCheck with your custom bash script.

**Comment by tofi86** [comment] 2016-05-03 21:30
I just stumbled upon this error when using homebrew EpubCheck on the commandline. But it also happens with EpubCheck build from Source.

It seems to be an issue with special chars (german umlauts, accents) in paths. See the attached log:

```
ToFi-MBP in ~/dev/Müller → java -jar epubcheck-4.0.1.jar 9783732523153.epub 
Verwendung der EPUB 3.0.1 Prüfungen
** OpenCL Error Notification: OpenCL Build Warning : Compiler build log:
warning: macro definitions used to build the precompiled header are missing
<built-in>:170:1: note: using this macro definition from precompiled header
#define cl_APPLE_fp64_basic_ops 1
^
<built-in>:169:1: note: using this macro definition from precompiled header
#define cl_khr_byte_addressable_store 1
^
<built-in>:164:1: note: using this macro definition from precompiled header
#define cl_khr_fp64 1
^
<built-in>:165:1: note: using this macro definition from precompiled header
#define cl_khr_global_int32_base_atomics 1
^
<built-in>:166:1: note: using this macro definition from precompiled header
#define cl_khr_global_int32_extended_atomics 1
^
<built-in>:167:1: note: using this macro definition from precompiled header
#define cl_khr_local_int32_base_atomics 1
^
<built-in>:168:1: note: using this macro definition from precompiled header
#define cl_khr_local_int32_extended_atomics 1
^

 **
Das EPUB enthält keine Fehler oder Warnungen.
Es ist valide.
EpubCheck abgeschlossen

 ToFi-MBP in ~/dev/Müller → cd ..

 ToFi-MBP in ~/dev → java -jar epubcheck-4.0.1.jar 9783732523153.epub 
Verwendung der EPUB 3.0.1 Prüfungen
Das EPUB enthält keine Fehler oder Warnungen.
Es ist valide.
EpubCheck abgeschlossen
```

The error appears when running epubcheck in `~/dev/Müller/` but it doesn't appear in `~/dev/`

German messages translate to "no errors or warnings" so the epub is being checked and is valid!

**Comment by rdeltour** [comment] 2019-01-21 12:30
I couldn't reproduce this on macOS Mojave 10.14.2, with OpenJDK 11.0.1+13:

```
in ~/Work/müller
$ java -jar epubcheck.jar issue169.epub 
Validating using EPUB version 2.0.1 rules.
No errors or warnings detected.
Messages: 0 fatal / 0 errors / 0 warnings / 0 info

EPUBCheck completed
```

@tofi86 can you please re-try to repro? If this has been fixed in recent versions of macOS or OpenJDK, then let's close this as `wontfix`.

**Comment by tofi86** [comment] 2019-10-28 20:55
I tried with Oracle Java SE 8 (u144) and 9.0.1 and also with AdoptOpenJDK 8 (u212) and 11.0.5 but I wasn't able to reproduce this on Mac OS 10.14.6.

**Closed by tofi86** 2019-10-28 20:55 UTC
Labels: status: waiting for feedback, type: bug
