### ISSUE TITLE
EPUBCHECK 4.2.0 Alpha 1 seems to crash on Win 10

### ISSUE THREAD

**Issue by brianrusnica** [w3c/epubcheck#940] opened 2019-01-14 21:55 UTC
I recently tested EPUBCHECK 4.2.0 Alpha 1 on my Windows 10 machine and received the attached errors when running EPUBCHECK.  I realize this is a slightly outdated version of Win 10 (due to corporate infrastructure management) but it ran all previous EPUBCHECK versions w/o issue. 

Machine Specs:
- Windows 10 Pro, Version 1703, OS build 15063.1324
- Java Version 8 Updated 45 (build 1.8.0_45-b14)

To Repro:
- run EPUBCHECK from the command line
- inspect output

Expected:
- list of EPUBCHECK Errors/Warnings

Actual:
- see attached.  
[epubcheck_4.2.0_crashlog_win10.txt](https://github.com/w3c/epubcheck/files/2757213/epubcheck_4.2.0_crashlog_win10.txt)
- string of messages like 
-- at com.thaiopensource.relaxng.pattern.DuplicateAttributeDetector.startChoice(DuplicateAttributeDetector.java:42)
--at com.thaiopensource.relaxng.pattern.ChoicePattern.checkRestrictions(ChoicePattern.java:30)
--at com.thaiopensource.relaxng.pattern.ChoicePattern.checkRestrictions(ChoicePattern.java:31)

**Comment by rdeltour** [comment] 2019-01-14 22:13
Thanks for the report! Would you be able to share the EPUB which made it crash? (If it's copyrighted material, you can send it privately over email and/or we could sign an NDA if needed).

**Comment by garconvacher** [comment] 2019-01-15 14:33
Same here with W10 pro 1803 (build 17134.523) and Java 9 (1.8.0_191-b12) with **all** EPUB (Moby Dick include)

**Comment by brianrusnica** [comment] 2019-01-15 15:05
Thanks @rdeltour  - as @garconvacher mentions, it appears to happen with all EPUBs I've tried, including a version of Moby Dick I just DL'd from this site: http://www.gutenberg.org/ebooks/2701

**Comment by mattgarrish** [comment] 2019-01-15 15:51
I'm running the same Windows setup as @garconvacher but with Java 10.0.1 (JRE 18.3) and not having any issues.

**Comment by TzviyaSiegman** [comment] 2019-01-15 15:57
I would love to test it but I can't even download it for "security" reasons. :(

**Comment by rdeltour** [comment] 2019-01-15 21:22
> sure thing, it is included in my original ticket

doh, of course 🤦‍♂️ 😄

**Comment by mattgarrish** [comment] 2019-01-15 21:35
If it helps, I tried downgrading to Java 1.8.0_45-b14 and I get the same behaviour. The latest Java 8 release runs fine, though. Definitely something in Java changed, but don't look to me to figure out what... :)

**Comment by rdeltour** [comment] 2019-01-15 22:47
@brianrusnica @garconvacher could you please retry running EPUBCheck with the options `-Xss512k -XX:ThreadStackSize=2048` added to the `java` command?

For instance:
```
> java -Xss512k -XX:ThreadStackSize=2048 -jar epubcheck.jar ..\moby-dick.epub
```

It seems to be a limitation of Jing (the RelaxNG engine), and the Nu HTML Checker [recommends adjusting the thread stack size](https://validator.github.io/validator/#usage) in that manner to work around it.

If you confirm it works, we could document that somewhere (or see if a better default can be set programmatically).

**Comment by rdeltour** [comment] 2019-01-15 22:51
(btw, I could reproduce the issue locally, using an up-to-date Windows 10 version 1803 and Java 1.8.0_161. Using the options mentioned did the trick in my case.)

**Comment by rdeltour** [comment] 2019-01-15 23:45
Well, as mentioned in the documentation of the `stackSize` option of Java's `Thread` constructor, this configuration really belongs to the JRE:

> Due to the platform-dependent nature of the behavior of this constructor, extreme care should be exercised in its use. The thread stack size necessary to perform a given computation will likely vary from one JRE implementation to another. In light of this variation, careful tuning of the stack size parameter may be required, and the tuning may need to be repeated for each JRE implementation on which an application is to run.

**Comment by rdeltour** [comment] 2019-01-15 23:56
I added a new ["Troubleshooting" section](https://github.com/w3c/epubcheck/wiki/Running#troubleshooting) to the command line documentation.

I will close this issue once I get confirmation this solution works for other.

**Comment by garconvacher** [comment] 2019-01-16 08:01
@rdeltour `java -Xss512k` work fine!

**Comment by brianrusnica** [comment] 2019-01-16 18:01
@rdeltour adding the "-Xss512k" option worked for me as well - I was able to run EPUBCHECK without any further issue.  Does this mean I should use this option for all future runs as well?

**Comment by rdeltour** [comment] 2019-01-16 19:48
Thank you @garconvacher and @brianrusnica for the confirmation.

> Does this mean I should use this option for all future runs as well?

Yes, correct.
The new schemas are apparently a bit more demanding on the thread stack size, and unless we bundle a launching script with EPUBCheck in the future, users will have to set the option themselves.

Also, the issue may not show up on more recent JVMs, which likely use a higher default thread stack size. There might be a difference between 32bits and 64bits JVMs.

**Comment by rdeltour** [comment] 2019-01-16 19:49
Closing this issue now. Feel free to continue the discussion on the comments, and thanks again for the report and feedback!

**Closed by rdeltour** 2019-01-16 19:49 UTC
Labels: status: completed, type: docs

**Comment by Wim-Stijnman** [comment] 2023-06-16 15:47
Encountered the same problem at june 16 2023 on a new windows 11 machine with all up-to-date software.
Applied suggested change in epubcheck file plugin.py like this:

    #----------------------------------------------------------------------
    # define epubcheck command line parameters
    #----------------------------------------------------------------------
    if is32bit:
        args = [java_path, '-Dfile.encoding=UTF8', '-Xss1024k', '-jar', epc_path, epub_path, '-q', '--json', '-']
    else:
        args = [java_path, '-Dfile.encoding=UTF8', '-Xss1024k', '-jar', epc_path, epub_path, '-q', '--json', '-']

Epubcheck now runs OK.

**Comment by jszabo98** [comment] 2023-11-01 23:53
-Xss512k also needed in openjdk 1.8.0_242 in windows 10 21h1
