### ISSUE TITLE
Should check that order of li items in EPUB 3 toc and page-list nav element follows spine

### ISSUE THREAD

**Issue by elmimmo** [w3c/epubcheck#353] opened 2014-04-15 14:52 UTC
epubcheck 3.0.1 is not currently enforcing the following requirements of the EPUB 3 spec:
1. Regarding [the toc `nav` Element](http://www.idpf.org/epub/301/spec/epub-contentdocs.html#sec-xhtml-nav-def-types-toc):
   
   > The order of `li` elements contained within the toc `nav` element must match the order of the targeted elements within each targeted EPUB Content Document, and must also follow the order of Content Documents in the Rendition's spine.
2. Regarding [the page-list `nav` Element](http://www.idpf.org/epub/301/spec/epub-contentdocs.html#sec-xhtml-nav-def-types-pagelist):
   
   > The order of `li` elements contained within a page-list `nav` structure must match the order of the actual pages inside each targeted EPUB Content Document and must also follow the order of Content Documents in the Rendition's spine.

**Comment by tofi86** [comment] 2017-09-18 18:49
Related to #717

**Comment by rdeltour** [comment] 2019-02-26 12:55
Duplicate of #888.

**Closed** 2019-02-26 12:55 UTC
Labels: type: duplicate
