### ISSUE TITLE
Error in ePubCheck 4.2.2 with an image issue ?

### ISSUE THREAD

**Issue by SeldomScene** [w3c/epubcheck#1153] opened 2020-06-22 15:12 UTC
**ePubCheck Log Display:**
Validating using EPUB version 3.2 rules.
java.lang.OutOfMemoryError: Java heap space
at java.awt.image.DataBufferByte.(Unknown Source)
at java.awt.image.ComponentSampleModel.createDataBuffer(Unknown Source)
at java.awt.image.Raster.createWritableRaster(Unknown Source)
at javax.imageio.ImageTypeSpecifier.createBufferedImage(Unknown Source)
at javax.imageio.ImageReader.getDestination(Unknown Source)
at com.sun.imageio.plugins.png.PNGImageReader.readImage(Unknown Source)
at com.sun.imageio.plugins.png.PNGImageReader.read(Unknown Source)
at javax.imageio.ImageIO.read(Unknown Source)
at javax.imageio.ImageIO.read(Unknown Source)
at com.adobe.epubcheck.bitmap.BitmapChecker.getImageSizes(BitmapChecker.java:145)
at com.adobe.epubcheck.bitmap.BitmapChecker.checkImageDimensions(BitmapChecker.java:269)
at com.adobe.epubcheck.bitmap.BitmapChecker.runChecks(BitmapChecker.java:321)
at com.adobe.epubcheck.opf.OPFChecker.checkItemContent(OPFChecker.java:455)
at com.adobe.epubcheck.opf.OPFChecker.runChecks(OPFChecker.java:159)
at com.adobe.epubcheck.opf.OPFChecker30.runChecks(OPFChecker30.java:88)
at com.adobe.epubcheck.ocf.OCFChecker.runChecks(OCFChecker.java:315)
at com.adobe.epubcheck.api.EpubCheck.doValidate(EpubCheck.java:224)
at com.adobe.epubcheck.tool.EpubChecker.validateFile(EpubChecker.java:221)
at com.adobe.epubcheck.tool.EpubChecker.processFile(EpubChecker.java:296)
at com.adobe.epubcheck.tool.EpubChecker.run(EpubChecker.java:158)
at com.adobe.epubcheck.tool.Checker.main(Checker.java:31)
Messages: 0 fatals / 0 errors / 0 warnings / 0 infos
EPUBCheck completed

Would it be possible to have more indication upon the faulty image ?

**Comment by rdeltour** [comment] 2020-06-23 07:28
Unfortunately this is not possible at the moment. `OutOfMemoryError` isn’t really predictable, and once it happens it's probably too late to log the image causing it. 
I'll dig into the code to see if it can be improved however. Would you be able to share an EPUB to help me reproduce ?

In any case, version 4.2.3 has just been released and should improve the memory consumption for that specific issue. Can you try it to see if it works?

**Comment by rdeltour** [comment] 2021-02-24 20:53
Closing the issue (for lack of reply, couldn't reproduce nor see obvious issues with the code). Feel free to reopen if the issue persists with v4.2.3+!

**Closed by rdeltour** 2021-02-24 20:53 UTC
Labels: priority: low, spec: all, status: stalled, type: improvement
