### ISSUE TITLE
EPUB Won't Validate - Two Error Codes 

### ISSUE THREAD

**Issue by atmosproductions** [w3c/epubcheck#1486] opened 2023-02-26 17:21 UTC
Hi

I've done all I can to try and get my epub ready to distribute but when validating, to my surprise, I have 182 errors which are almost exclusively ERROR(RSC-020) and ERROR(RSC-005). I have absolutely 0 coding knowledge or experience and I'm so desperate to get this finished and validated. Any help would mean the world to me. I have been creating my eBook in InDesign and I think the issue is to do with the hyperlinks I added for the in-document contents page. I have created a text anchor for each chapter and a destination too. The text anchor hyperlinks work fine when tested on Apple Books and Kindle Previewer 3 so I don't get what to do.

Some of my full error codes can be seen below:

ERROR(RSC-005): ./books/Bo/databases/eBookIt/temp_uploads/1677430331.epub/OEBPS/Poetry_for_the_Blind_(978-1-7393014-8-4)_[Interior_-_Reflowable].xhtml(76,148): Error while parsing file: value of attribute "href" is invalid; must be a string matching the regular expression "[ - ]*" or must be a URI

ERROR(RSC-020): ./books/Bo/databases/eBookIt/temp_uploads/1677430331.epub/OEBPS/Poetry_for_the_Blind_(978-1-7393014-8-4)_[Interior_-_Reflowable].xhtml(76,148): "Poetry_for_the_Blind_(978-1-7393014-8-4)_[Interior_-_Reflowable]-27.xhtml#_idTextAnchor026" is not a valid URI.

**Comment by mattgarrish** [comment] 2023-02-26 22:58
Just looking at your file name:

`Poetry_for_the_Blind_(978-1-7393014-8-4)[Interior-Reflowable].xhtml`

You have to escape brackets in the links (%5B and %5D).

In other words, I expect you have links like this:

`<a href="Poetry_for_the_Blind_(978-1-7393014-8-4)[Interior-Reflowable].xhtml#idTextAnchor026">`

But to be valid the file name needs to be escaped to:

`<a href="Poetry_for_the_Blind_(978-1-7393014-8-4)%5BInterior-Reflowable%5D.xhtml#idTextAnchor026">`

The links may work in some reading systems without the brackets properly escaped, but better to encode them for those that don't handle invalid URLs.

**Comment by atmosproductions** [comment] 2023-02-27 14:12
> Just looking at your file name:
> 
> `Poetry_for_the_Blind_(978-1-7393014-8-4)[Interior-Reflowable].xhtml`
> 
> You have to escape brackets in the links (%5B and %5D).
> 
> In other words, I expect you have links like this:
> 
> `<a href="Poetry_for_the_Blind_(978-1-7393014-8-4)[Interior-Reflowable].xhtml#idTextAnchor026">`
> 
> But to be valid the file name needs to be escaped to:
> 
> `<a href="Poetry_for_the_Blind_(978-1-7393014-8-4)%5BInterior-Reflowable%5D.xhtml#idTextAnchor026">`
> 
> The links may work in some reading systems without the brackets properly escaped, but better to encode them for those that don't handle invalid URLs.

Hi many thanks, changing the file name to take out the square brackets worked a treat. Many thanks! I'm now having an issue with the paragraph spacing on kindle as it seems to be condensing the assigned 5mm spacing to something smaller. Any ideas of how I could overcome this issue? It's the last thing I need to do before the book can be distrubuted.

**Comment by mattgarrish** [comment] 2023-02-27 14:22
> Any ideas of how I could overcome this issue?

Sorry, no, I don't do style debugging. You'll likely find more help for those kinds of issues by asking the #epdrctn group on twitter.

**Comment by atmosproductions** [comment] 2023-02-27 16:32
> > Any ideas of how I could overcome this issue?
> 
> Sorry, no, I don't do style debugging. You'll likely find more help for those kinds of issues by asking the #epdrctn group on twitter.

No worries. I just managed to sort it all out so the book is done. Very grateful for your help Matt. If there is anything I can do to repay you for your help. Let me know, Atmos

**Comment by rdeltour** [comment] 2023-03-06 09:36
Closing this issue, as it is not a bug with EPUBCheck.

**Closed by rdeltour** 2023-03-06 09:36 UTC
