### ISSUE TITLE
Found a reference to a resource that is not a spine item?

### ISSUE THREAD

**Issue by pekka2** [w3c/epubcheck#1330] opened 2022-04-18 11:57 UTC
Hey
I have a strange mistake. All locations that link to "alkusanat.html" will receive the error message "Found a reference to a resource that is not a spine item"
However, this file is listed in the content.opf file.
For some reason, the program cannot find the alkusanat.html file.
I understand that this error can occur if there is an error in the top line of the files, but the validator does not report any other errors.

**Comment by rdeltour** [comment] 2022-04-18 12:22
The message you get is typically reported when EPUBCheck detects a hyperlink do a document that is not listed in the `spine` element of the package document.

It's hard to tell what's exactly wrong in your case without looking at the files or the exact error message. My guess is that the document "alkusanat.html" is not listed in the spine.

**Comment by rdeltour** [comment] 2022-04-18 12:24
I'm closing this issue as `invalid`, as this is apparently not a bug with EPUBCheck. But feel free to keep on commenting here.

Also, please note that this issue tracker is reserved to bug reports and feature requests, and should not be used for user support requests 😊.

**Closed by rdeltour** 2022-04-18 12:24 UTC
