### ISSUE TITLE
Possible incorrect language error reported on (inline) SVGs

### ISSUE THREAD

**Issue by ThomasR128** [w3c/epubcheck#1233] opened 2021-04-03 07:45 UTC
An SVG (inline in this case) declared as
    `<svg xmlns="http://www.w3.org/2000/svg" xml:lang="en" lang="en">    …    </svg>`
is being reported as an error ("`lang` attribute not permitted here") by epubcheck 4.2.4/4.2.5

Btw, this is the exact example given in the [Daisy KB](http://kb.daisy.org/publishing/docs/html/svg.html#ex). According to the Explanation section of this document, _"The lang attribute should also be specified in case the SVG is not interpeted by an XML parser."_

The [SVG spec](https://www.w3.org/TR/SVG2/struct.html#LangSpaceAttrs) allows both `lang` and `xml:lang`, so I don't think this should be reported as an error.

**Comment by rdeltour** [comment] 2022-12-23 18:25
I could not reproduce the issue with recent builds; this was likely fixed by HTML schema updates.

**Closed** 2022-12-23 18:25 UTC
Labels: type: unverified
