### ISSUE TITLE
Errors for nested <div> in epub 3

### ISSUE THREAD

**Issue by tthkbw** [w3c/epubcheck#1287] opened 2021-11-02 15:05 UTC
I have created an epub 3 file that contains nested `<div>` elements. epubcheck throws errors for all of these:

```
ERROR(RSC-005): ./paged_epubs/xxx.epub/OEBPS/c01_r1.xhtml(32,231): Error while
 parsing file: element "div" not allowed here; expected the element end-tag, text, element "a", "abbr", "area
", "audio", "b", "bdi", "bdo", "br", "button", "canvas", "cite", "code", "data", "datalist", "del", "dfn", "e
m", "embed", "epub:switch", "i", "iframe", "img", "input", "ins", "kbd", "label", "link", "map", "mark", "met
a", "meter", "ns1:math", "ns2:svg", "object", "output", "picture", "progress", "q", "ruby", "s", "samp", "scr
ipt", "select", "small", "span", "strong", "sub", "sup", "template", "textarea", "time", "u", "var", "video" 
or "wbr" (with xmlns:ns1="http://www.w3.org/1998/Math/MathML" xmlns:ns2="http://www.w3.org/2000/svg") or an e
lement from another namespace
```

These errors do not affect the display of the added nested `<div>` element in ebook readers I have tested (limited to Calibre and Apple Books at this point). 

Nested `<div>` is allowed in html, and I don't find anything about not allowing them in epub 3. 

What am I missing?

**Comment by rdeltour** [comment] 2021-11-02 16:48
Thanks for the report 😊
Are you able to send us a file sample to help us reproduce the issue?
Also, have you checked with the [HTML validator](https://validator.w3.org/nu/)? (it may provide more context).

**Comment by mattgarrish** [comment] 2021-11-02 17:46
Just going by the error message, it appears the `div` is embedded where only phrasing content is allowed.

Using markup like this `<p> ... <div> ... </div> ... </p>` would generate this error, for example.

**Comment by tthkbw** [comment] 2021-11-03 12:25
Thanks for the quick feedback. I am traveling the rest of this week, so can only take the time for a brief reply.

@mattgarrish - I think your hint may have led me to the problem, which, as I expected, is with my code. 

Although I routinely create nested <div> elements, not all of them generate errors from eubcheck. I now see that those that do are nesting the <div> elements within <i></i> elements. 

That’s my bug, and I’ll fix it next week. I’ll report back then.

**Comment by tthkbw** [comment] 2021-11-03 13:35
Okay, so I really couldn’t leave this alone. I found a quick fix in my code and I am now generating error-free epubs again.

Thanks for the help, and for epubcheck.

**Comment by rdeltour** [comment] 2021-11-03 14:35
OK thanks for confirming! I'm closing this issue as `invalid` (not a bug in EPUBCheck).

**Closed by rdeltour** 2021-11-03 14:35 UTC
Labels: type: invalid
