### ISSUE TITLE
ARIA attributes should be allowed on SVG elements

### ISSUE THREAD

**Issue by brianagina** [w3c/epubcheck#846] opened 2018-05-15 13:42 UTC
I have been working on making an epub file accessible. Finally, the DAISY ACE showed no violations arising from the epub file after validation. On validating via the epubcheck 4.0.2 , I got 3 errors arising from parsing the epub file. The errors were as a result of making an image accessible: 

**1. Error while parsing file 'attribute "aria-label" not allowed here
2. Error while parsing file 'attribute "role" not allowed here, and 
3. Error while parsing file 'attribute "alt" not allowed here**

How can I solve this?

**Comment by JayPanoz** [comment] 2018-06-27 09:54
@tofi86 Not sure about that but it may well be SVG 1.1 (the one we use in the EPUB spec) versus SVG 2.0. Maybe that can help with the review.

Aria attributes [were added in SVG 2.0](https://svgwg.org/svg2-draft/embedded.html#ImageElement), they [did not appear in SVG 1.1](https://www.w3.org/TR/SVG11/struct.html#ImageElement). As for `alt`, an error is expected since you should use `<title>` ([see SVG Graphics](https://www.w3.org/WAI/tutorials/images/tips/)). 

Note 1.1 is somewhat painful in some cases e.g. [custom `data-*` attribute](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/data-*), which works without any issue but will throw an error in ePubCheck as it is strictly speaking SVG 2.0 (so you must create a namespace etc.). That being said, “[SVG2, it’s complicated](https://css-tricks.com/svg-2-conundrum/).”

**Comment by rdeltour** [comment] 2019-02-26 10:39
The `alt` attribute is not allowed on SVG `image` elements, but since SVG 2 ARIA `role` and `aria-*` (state and properties) attributes should be allowed indeed.

I could reproduce that this is still reported as an error on v4.2.0-beta.

**Comment by rdeltour** [comment] 2019-02-26 10:48
I added a test case in branch `fix/846/svg-aria`.

@mattgarrish can you please confirm that ARIA attributes should indeed be supported? (in light of w3c/publ-epub-revision#1219)

**Comment by JayPanoz** [comment] 2019-02-26 10:58
FWIW, as someone who spent an entire workday adding – do the right a11y thing – then removing ARIA attributes on hundreds of SVGs a few years ago, I’m highly in favour of supporting them (and there are so many how-tos using those irl that it’s kinda frustrating to discover they will create errors once it’s done).

**Comment by mattgarrish** [comment] 2019-02-26 12:13
Right, let's not take the attributes out and get into a game of modifying the official schemas. The end resolution was that we'll sort of pretend we're referencing 1.1 for spec purity but the reality is we'll actually allow whatever the browsers are now accepting, which as @dauwhe pointed out in https://github.com/w3c/publ-epub-revision/issues/1219#issuecomment-467128476 is closer to SVG2.

**Comment by rdeltour** [comment] 2019-02-26 12:16
> Right, let's not take the attributes out and get into a game of modifying the official schemas.

Just for clarifications: these attributes seem to be **rejected** by the new schemas in 4.2.0-beta. That is likely due to how we integrate these when validating as SVG-only, I'll have a deeper look.

**Comment by mattgarrish** [comment] 2019-02-26 13:01
Seems to be working for me. There are elements that the attributes aren't allowed on, but I haven't seen them rejected.

**Comment by rdeltour** [comment] 2019-02-26 13:07
Have you tried the [test case in branch `fix/846/svg-aria`](https://github.com/w3c/epubcheck/blob/fix/846/svg-aria/src/test/resources/30/single/svg/valid/aria-attributes.svg)?

**Comment by mattgarrish** [comment] 2019-02-26 13:21
No, I was using the sous le vent book from the samples and applying roles and attributes to various elements without problem. It must be a localized bug.

**Comment by mattgarrish** [comment] 2019-02-26 13:26
It doesn't report `role` as an error, only `aria-label`.

Looking at the schema, wouldn't the ? at the end here be the culprit:

> (common.attrs.aria.implicit.img | common.attrs.aria)?,

**Comment by mattgarrish** [comment] 2019-02-26 13:27
Sorry, that's from attlist.image in svg-image.rnc in case it's not obvious.

**Comment by rdeltour** [comment] 2019-02-26 13:44
> Looking at the schema, wouldn't the ? at the end here be the culprit

You mean it should be `*` instead right? Possibly. I'm surprised however this hasn't been raised already and fixed in validator.nu. The pattern seems to be used in various other elements.

**Comment by rdeltour** [comment] 2019-02-26 13:48
For ref, here's [the validator.nu commit](https://github.com/validator/validator/commit/3530d33b339a64fb3dd76673257d1fb7b930b9ea) which introduced it.

**Comment by mattgarrish** [comment] 2019-02-26 14:02
I was thinking it was unnecessary, but that's probably not the issue after running a couple of tests. It also validates fine in the online validator, which presumably is using these same schemas. I'll keep sniffing around and see if I can make any sense of what is happening.

**Comment by mattgarrish** [comment] 2019-02-26 22:17
For the record, we were missing this line from nu validator driver file:

> `SVG.Core.attrib &= aria.global?`

So only the attributes defined in common.attrs.aria were allowed, which is why we both seemed to be right in what we were checking. :)

**Closed** 2019-02-26 23:22 UTC
Labels: status: completed, type: bug
