### ISSUE TITLE
Incorrect links for epubcheck documentation

### ISSUE THREAD

**Issue by kaos-ocs** [w3c/epubcheck#1283] opened 2021-09-27 01:05 UTC
Starting from `https://w3c.github.io/epubcheck/docs/` . Lots of links like `https://w3c.github.io/publishing/epubcheck/docs/cli/` get 404. The correct link is `https://w3c.github.io/epubcheck/docs/cli/` - but that is just one example of many broken links.

**Comment by rdeltour** [comment] 2021-09-27 08:06
Thanks for the report 😊. This issue is known, it's a duplicate of #1268.

In fact the canonical URL of the site is https://www.w3.org/publishing/epubcheck/. Due to limitations of the current hosting solution, redirection from `github.io` to `w3.org` cannot be configured. 

I'm closing this issue (duplicate). But could you please let me know how you reached the `github.io` site in the first place instead of the `w3.org` one?

**Closed** 2021-09-27 08:06 UTC
Labels: type: duplicate

**Comment by kaos-ocs** [comment] 2021-09-27 13:14
`https://www.w3.org/publishing/epubcheck/docs/installation` gets 301 -> `https://w3c.github.io/epubcheck/docs/installation/` and it's downhill from there.

**Comment by rdeltour** [comment] 2021-09-27 13:34
Ah I see. The missing slash at the end of the URL causes the redirection to redirection. I'll try to fix all the links where that happens. Thanks for the good catch! 👍
