### ISSUE TITLE
OPF-053 syntax WARNING

### ISSUE THREAD

**Issue by MMImedia** [w3c/epubcheck#1072] opened 2019-08-27 16:54 UTC
Mere civilian here trying to publish an ebook.

Prepared in InDesign 2018, saved as .epub and when run through ePUBChecker up pops a Warning - OPF-053 Date value - syntax

This is pointing to my signing off the Preface with my name followed by August 2019.

Why? How? can "August 2019" cause such problems?

**Comment by rdeltour** [comment] 2019-08-27 19:04
The EPUB Packages spec says that the [value of `dc:date` metadata should conform to a specific syntax](https://www.w3.org/publishing/epub3/epub-packages.html#sec-opf-dcdate), specifically the one defined in the [W3C Date and Time Formats note](https://www.w3.org/TR/NOTE-datetime).
"August 2019" does not, which is probably the reason why you get a warning.

**Comment by rdeltour** [comment] 2019-08-27 19:10
I'm closing this issue as `invalid`, since EPUBCheck’s behavior is apparently correct here. Feel free to reopen if you disagree.

Also, please note that this issue tracker is expected to be used to report bugs or feature requests, but should not be used for user support requests. The EPUB 3 community is currently pondering where these user discussions should happen instead (see issue [“How to help people who have questions about EPUBs?”](https://github.com/w3c/publ-cg/issues/88)).

**Comment by MMImedia** [comment] 2019-08-27 19:47
Techie snobbery. Love it!

**Comment by MMImedia** [comment] 2019-08-27 20:01
BTW - that is a “bug” when the check picks up body text and flags it as if it’s appearing as the publication dat. Thankful it didn’t happen in the rest of the book as there are many dates.

**Comment by rdeltour** [comment] 2019-08-27 20:32
> Techie snobbery

I honestly don’t see what’s snobbish in my reply 😮🤔… I politely clarified the purpose of this issue tracker, __after__ having taken the time to give explain the cause of your validation warning, and gave pointers to the related specifications.

But you’re new here and a “mere civilian” 😁 so apologies if it sounded off-putting! 😊 Suggestions on how or where to handle or redirect user requests are always welcome.

> that is a “bug” when the check picks up body text and flags it as if it’s appearing as the publication dat. Thankful it didn’t happen in the rest of the book as there are many dates.

Do you have a book sample that you can share to check if this is bug? All I can say now is that the warning in question  (`OPF-053`) is only raised for the values of `dc:date` metadata, which only occur in the Package Document (.opf) of the EPUB. So it definitely does not look like a bug.

That this piece of metadata is set to some body text is probably a side-effect of your production tool. You could also raise the question on InDesign’s support channels.

**Closed** 2019-08-27 20:40 UTC
Labels: type: invalid

**Comment by rdeltour** [comment] 2019-08-27 20:42
(effectively closing as I forgot to close last time. but again if you do think there’s a bug and if you have a sample file to check or reproduce the error, you can keep on discussing here by all means!).

**Comment by MMImedia** [comment] 2019-08-27 20:44
Will never return.

**Comment by laudrain** [comment] 2019-08-28 07:00
@MMIMmedia EPUBCheck is just verifying the conformance of your .epub file to the specifications. 

Any warning or error reported by EPUBCheck is an alert that the file may not render properly and deceive your readers. 
Romain gave here explanations but without a look inside the EPUB cannot be more precise on where is the problem in your file. 

By the way, EPUB specifications are established by a large community and if you have some specific needs, please send an issue in EPUB3 Community Group.

**Comment by JayPanoz** [comment] 2019-09-03 11:06
Just for the sake of documenting the root issue – I can somewhat relate because that popped-up an awful lot during ID training when I was doing that. 

This is the metadata panel (sorry, in French):

![Capture d’écran 2019-09-03 à 12 51 41](https://user-images.githubusercontent.com/12599652/64167936-c0db2580-ce4a-11e9-90b1-3b6cbcbae6fa.png)

And there’s nothing telling users “the recommended format is [example]” or even a pre-populated entry with the current date for instance. 

They won’t attempt to transform it either, here’s the output: 

![Capture d’écran 2019-09-03 à 12 52 57](https://user-images.githubusercontent.com/12599652/64168019-f1bb5a80-ce4a-11e9-8029-2e4ac4c46ae7.png)

**Comment by nicknnator** [comment] 2022-09-01 01:42
Thanks, Jay for the image. Romain is technically correct, and that is what MMImedia is confusing for "Techie Snobberie"... While pointing out the standard that is being followed is an acceptable answer for this forum MMIMedia was looking for the "civilian" answer, which is "when you save your book as an e-book, click on the Metadata link on the sidebar and make sure your date conforms to the `[W3 Date and Time Formats](https://www.w3.org/TR/NOTE-datetime)` ", as a software analyst I also walk that fine line between customer friendly and tech snob.
