### ISSUE TITLE
ERROR for role="doc-epigraph"

### ISSUE THREAD

**Issue by flittle8** [w3c/epubcheck#1055] opened 2019-07-09 09:38 UTC
I'm getting an error when role="doc-epigraph" is used on a section tag. here is the code and attached error. I'm on Epub-check 4.2.1.

```
 <section epub:type="epigraph" role="doc-epigraph">
    <h1 id="epigraph">Epigraph</h1>
    <blockquote class="quote">
    <p>I want you ot know, if you ever read this, there was a time when I would rather have had you by my side than any one of these words; I would rather have ahd you by my side than all the blue in the world.</p>
    <p><cite>—Maggie Nelson</cite></p>
    </blockquote>
    </section>
```

![Screen Shot 2019-07-09 at 10 36 19 AM](https://user-images.githubusercontent.com/23460746/60877419-af541380-a235-11e9-9c0f-30c697df1a7a.png)

**Comment by rdeltour** [comment] 2019-07-09 11:53
Currently, `doc-epigraph` is not allowed on `section` elements, as per the [ARIA in HTML](https://www.w3.org/TR/html-aria/#section) specification, so EPUBCheck is correct in reporting that.

Note that whether `doc-epigraph` should be allowed on `section` elements is still open for debate by the Digital Publishing Working Group, so this situation might change in the future…

See also daisy/ace#234 where this was discussed recently.

**Comment by rdeltour** [comment] 2019-07-09 11:54
Closing as `invalid` as EPUBCheck behaves as intended. Feel free to keep on commenting!

**Comment by flittle8** [comment] 2019-07-09 11:54
@rdeltour thanks, good to know!

**Closed by rdeltour** 2019-07-09 11:54 UTC
Labels: type: invalid
