### ISSUE TITLE
<a> inside <a>

### ISSUE THREAD

**Issue by eric-muller** [w3c/epubcheck#1345] opened 2022-08-04 17:24 UTC
[java] ERROR(RSC-005): results/000459/10_melanges_de_litterature.epub/OEBPS/content-table.xhtml(33,180): Error while parsing file: The a element must not appear inside a elements.

I can understand how `<a href=..>` inside `<a href=…>` warrant an error (and even that is not entirely clear), but in my case, it's `<a id=…>` inside `<a href=…>`: the `<a id=…>` is for a page boundary, and the `<a href=…>` is for an entry in a table of content, said entry spanning two pages; see pages 466/467 at <https://gallica.bnf.fr/ark:/12148/bpt6k2026528/f465.item> for an actual book.  That seems a perfectly fine use of nested `<a>`.

**Comment by mattgarrish** [comment] 2022-09-01 10:47
No nesting of `a` elements is a requirement of the HTML specification:

> [Content model](https://html.spec.whatwg.org/multipage/dom.html#concept-element-content-model):
> [Transparent](https://html.spec.whatwg.org/multipage/dom.html#transparent), but there must be no [interactive content](https://html.spec.whatwg.org/multipage/dom.html#interactive-content-2) descendant, `a` element descendant, or descendant with the [tabindex](https://html.spec.whatwg.org/multipage/interaction.html#attr-tabindex) attribute specified.

https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element

They don't want people using `a` tags as anchor points anymore. If you omit `href` it's considered a placeholder link now:

> If the [a](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-a-element) element has no [href](https://html.spec.whatwg.org/multipage/links.html#attr-hyperlink-href) attribute, then the element [represents](https://html.spec.whatwg.org/multipage/dom.html#represents) a placeholder for where a link might otherwise have been placed, if it had been relevant, consisting of just the element's contents.

This is outside our control. You'd have to convince the HTML folks to change the definition and content model of the `a` element as epubcheck is just reporting the issue per the html schemas.

To avoid this problem, we recommend using `span` and `div` for page break markers.

**Comment by rdeltour** [comment] 2022-09-01 12:21
Thanks @mattgarrish for the detailed answer and pointers. I'm closing the issue as invalid, as it is not a bug in EPUBCheck. 

@eric-muller feel free to keep commenting here!

**Closed** 2022-09-01 12:22 UTC
Labels: type: invalid

**Comment by eric-muller** [comment] 2022-09-01 12:23
First, sorry for missing the fact that Github uses markdown.

Thanks for pointing out that `a` is no longer to be used for anchors, I wasn't aware of that.
