### ISSUE TITLE
OPF-001 Issue; Version Issue in OPF (Package)

### ISSUE THREAD

**Issue by Sudhakar2007** [w3c/epubcheck#1188] opened 2020-10-21 12:03 UTC
Dear All,

I run the ePUB 3.2 version file in the ePUB checker 4.2.2 and get the following error message.

ERROR(OPF-001): new.epub/OEBPS/content.opf(-1,-1): There was an error when parsing the EPUB version: Version not supported.

XHTML Package code as follows:
<package xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns="http://www.idpf.org/2007/opf" xmlns:dcterms="http://purl.org/dc/terms/" version="3.2" xml:lang="en" unique-identifier="p9780124046320">

Could you please provide me a solution to resolve this issue.

Thanks,
Sudhakar

**Comment by Sudhakar2007** [comment] 2020-10-21 12:05
XHTML Package code as follows:
&lt;package xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns="http://www.idpf.org/2007/opf" xmlns:dcterms="http://purl.org/dc/terms/" version="3.2" xml:lang="en" unique-identifier="p9780124046320"&gt;

**Comment by dauwhe** [comment] 2020-10-21 12:30
The `version` attribute on the `package` element must be `3.0` for all versions of EPUB 3.

**Comment by Sudhakar2007** [comment] 2020-10-21 12:33
Thanks, Dauwhe.

How to identify that the ePub is created in version 3.2 i.e. in which place I have to look?

Best,
Sudhakar

**Comment by dauwhe** [comment] 2020-10-21 12:37
> How to identify that the ePub is created in version 3.2 i.e. in which place I have to look?

There's no need to. I think of EPUB 3 much like I think of HTML5. The HTML5 spec changes, but there's no version number for the content. Everything is designed to be backward-compatible.

**Comment by mattgarrish** [comment] 2020-10-21 12:43
We may want to make it clearer in the specification that the number doesn't change now that we've abandoned the idea of ever incrementing the version,.

Closing this issue since it is not a bug. For general questions like this about EPUB, forums like [twitter](https://twitter.com/hashtag/eprdctn), [mobilereads](https://www.mobileread.com/forums/forumdisplay.php?f=179) and [stackexchange](https://ebooks.stackexchange.com/?tags=epub) are better starting places.

**Closed by mattgarrish** 2020-10-21 12:43 UTC
