### ISSUE TITLE
EpubCheck fails during update check

### ISSUE THREAD

**Issue by Wim-Stijnman** [w3c/epubcheck#1305] opened 2022-02-26 21:00 UTC
EpubCheck version 0.4.6.1, run from Sigil 1.9.0

![New Picture](https://user-images.githubusercontent.com/100492206/155858806-26e36684-eb61-4669-a003-5c5747316385.jpg)

**Comment by rdeltour** [comment] 2022-02-28 08:33
This looks like an issue with Sigil rather than EPUBCheck itself. I recommend you ask the Sigil developers, or [report an issue on their tracker](https://sigil-ebook.com/sigil/issues/).

I'm closing this issue as `invalid`, as this is not a bug.
Feel free to keep on commenting, or to reopen if it appears this is actually a bug in EPUBCheck!

**Closed by rdeltour** 2022-02-28 08:33 UTC

**Comment by Wim-Stijnman** [comment] 2022-02-28 09:09
A new release of epubcheck has resolved the problem, which makes it unlikely that sigil caused the problem. Anyway, case closed.Wim StijnmanVerzonden vanaf Samsung-tablet.
-------- Oorspronkelijk bericht --------Van: Romain Deltour ***@***.***> Datum: 28-02-22  09:33  (GMT+01:00) Aan: w3c/epubcheck ***@***.***> Cc: Wim-Stijnman ***@***.***>, Author ***@***.***> Onderwerp: Re: [w3c/epubcheck] EpubCheck fails during update check (Issue #1305) 
This looks like an issue with Sigil rather than EPUBCheck itself. I recommend you ask the Sigil developers, or report an issue on their tracker.
I'm closing this issue as invalid, as this is not a bug.
Feel free to keep on commenting, or to reopen if it appears this is actually a bug in EPUBCheck!

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/w3c/epubcheck/issues/1305#issuecomment-1054012195",
"url": "https://github.com/w3c/epubcheck/issues/1305#issuecomment-1054012195",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
