### ISSUE TITLE
Invalid rejection of "value" parameter inside <li>

### ISSUE THREAD

**Issue by Scribliotech** [w3c/epubcheck#1285] opened 2021-10-21 04:21 UTC
For discontinuous lists, it is necessary to be able to start a list item with a specific value. Per W3 convention, one of the valid means for doing this is using the `value` parameter as in: `<li value = 10>` (e.g., https://www.w3schools.com/tags/att_li_value.asp and https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li). However, epubcheck rejects this proper formation with the error message: 

`ERROR(RSC-005): test_file.html(21,19): Error while parsing file: attribute "value" not allowed here; expected attribute "class", "dir", "id", "lang", "style", "title" or "xml:lang"`

This is incorrect. "value" is allowed in the places where epubcheck reports this error and every e-reader we've tested that supports the `<li>` attribute also supports tested the "value" parameter. 

Please remove this error and return valid response when this parameter is used.

**Comment by mattgarrish** [comment] 2021-10-21 11:17
I haven't been able to reproduce an error on an `ol` element, which is the only list type in which you can use a `value` attribute on list items per the html specification:

> If the element is not a child of an ul or menu element: value — Ordinal value of the list item

https://html.spec.whatwg.org/multipage/grouping-content.html#the-li-element

A couple of things to check would that you aren't using it on `li` elements in an unordered list and that you have the latest version of epubcheck. Otherwise, could you provide a sample of the markup that causes the error?

**Comment by rdeltour** [comment] 2021-10-21 13:13
I cannot reproduce that with the latest version of EPUBCheck. Can you please tell us which version you're using? Thanks!

**Comment by rdeltour** [comment] 2021-10-21 19:35
> By that prose, it seems like epubcheck should allow all XHTML modules

only if they are used in XML islands, if I understand correctly.
I’m not sure if EPUBCheck allows that (I’d need to have a deeper look), but that wouldn’t be much practical for publishers in any case.

**Comment by rdeltour** [comment] 2021-11-12 09:28
I'm closing this issue as `invalid`, as this is not a bug with EPUBCheck.
Feel free to keep on commenting, or to reopen if you disagree!

**Closed by rdeltour** 2021-11-12 09:28 UTC
Labels: status: waiting for feedback
