### ISSUE TITLE
EPUB Checker Execution Issue

### ISSUE THREAD

**Issue by Bala6644** [w3c/epubcheck#1541] opened 2023-08-24 07:38 UTC
The EPUB validation has failed while using the option "--version" in the command line argument and getting the default message in the log file even if there are any errors or warnings in the source EPUB file. The previous version 5.0.1 correctly indicated the error/warning with version details. Kindly check and assist us to resolve this issue. 

EPUBCheck v5.1.0 Messages: 0 fatals / 0 errors / 0 warnings / 0 infos / 0 usages EPUBCheck completed 

Usage C:\Users\euser>java -jar -Xss1024k "C:\Localfiles\Support\ePUB-Checker\5.1.0\epubcheck.jar" "C:\Localfiles\Support\ePUB-Checker\test.epub" --version > "C:\Localfiles\Support\ePUB-Checker\test.log" 2>&1

**Comment by rdeltour** [comment] 2023-08-31 15:56
Duplicate of #1533

**Closed by rdeltour** 2023-08-31 15:56 UTC
Labels: type: duplicate
