### ISSUE TITLE
Saved epubs when not using -save mode

### ISSUE THREAD

**Issue by mattgarrish** [w3c/epubcheck#1351] opened 2022-09-20 16:53 UTC
I just noticed with the beta 2 release that when I run epubcheck on an expanded directory I end up with a packaged ".epub" file whether or not I also specify the -save option.

This is on Windows 10 using java se 17.0.4.1.

**Comment by rdeltour** [comment] 2022-12-06 13:02
@mattgarrish I could not reproduce this in v5.0.0-beta-3. Can you confirm?

**Comment by rdeltour** [comment] 2022-12-23 17:36
Closing this one, as it could not be reproduced with the latest builds. @mattgarrish feel free to reopen if needed!

**Closed by rdeltour** 2022-12-23 17:36 UTC
Labels: status: in discussion, type: unverified
