### ISSUE TITLE
Font issues

### ISSUE THREAD

**Issue by santoch** [w3c/epubcheck#391] opened 2014-07-11 23:13 UTC
We have two font related questions:

·         Web-fonts: Currently ePubCheck tracks usage of embedded and referenced fonts in the publication metadata in the xml and json output files. But, ePubChecl emits a FATAL message when web fonts are actually included in an ePub, stating that external resources are not allowed (message RSC-006, “ERROR(RSC-006): .\EmbeddedFontTest.epub/OPS/A.html(7,109): Remote resource reference not allowed; resource must be placed in the OCF.” Are web fonts intended to be permitted? That’s implied by their presence in the publication metadata. The tracking of font types happened in the css/csshandler.java source file.

·         Fonts in Trident-based reading systems (on Windows using the Trident Webview, or when web-based reading is hosted in Internet Explorer): Trident requires the permissions of any embedded fonts to be “installable” (fsType flag in the Opentype OS/2 table). They don’t respect print/preview permissions and won’t load the font. We’ve attempted to detect and warn when improperly licensed fonts are embedded in an epub, but the performance cost to determine the license rights present in a font is high. Is this check work performing? Is adding a command line flag to enable this check a worthwhile mediation for the performance hit?

Thanks,
Steve & Howard-

**Comment by rdeltour** [comment] 2019-02-26 12:54
The first item seems to be a duplicate of #871.

As for the second item, I believe this is out of scope for EPUBCheck.

**Closed** 2019-02-26 12:54 UTC
Labels: type: duplicate
