### ISSUE TITLE
WARNING (NAV-011): Misfiring when endnotes will be moved together per chapter in single file

### ISSUE THREAD

**Issue by manojksharma80** [w3c/epubcheck#1101] opened 2020-02-03 09:29 UTC
Hi all,

I feel that EPUBCheck v4.2.2 is misfiring warnings when we insert page numbers in sequence in page-list nav order and the order of file naming are different from spine order:

<nav epub:type="page-list">
    <ol>
        <li id="page_60"><a href="../xhtml/chapter004.xhtml#page_60">60</a></li>
        <li id="page_61"><a href="../xhtml/chapter004.xhtml#page_61">61</a></li>
        <li id="page_62"><a href="../xhtml/notes.xhtml#page_62">62</a></li>
        <li id="page_63"><a href="../xhtml/notes.xhtml#page_63">63</a></li>
        <li id="page_64"><a href="../xhtml/chapter005.xhtml#page_64">64</a></li>
        <li id="page_65"><a href="../xhtml/chapter005.xhtml#page_65">65</a></li>       
    </ol>
</nav>

![Untitled](https://user-images.githubusercontent.com/60595213/73642873-847d5100-4698-11ea-8989-87eb774daba6.png)

Actually, all endnotes are paginated at end of the each chapter in the printed book, but for ebook we have instruction to move all endnotes together per chapter in a single file (notes.xhtml) file and set it at end of the book. When we insert page number of the book in page-list in sequential order then page number 62 and 63 which is acutely belongs to chapter004.xhtml but now has been moved to notes.xhtml should be set between the chapter004 and chapter005 as the file naming “notes.xhtml” - epubcheck-v4.2.2 raised a warning that the nav order of notes.xhtml and chapter005.xhtml are different from spine order i.e. notes.xhtml should not come before the chapter005.xhtml, see example above.

In the page-list nav order, EPUBCheck v4.2.2 should be check only page sequences in page-list not file naming where the pages are present. Please correct if I am wrong.

Could you please check and suggest how to correct these warnings?

**Comment by rdeltour** [comment] 2020-02-04 11:15
Hi @manojksharma80, thanks the report.

The core of the issue is that EPUB *does* require the page list to be matching the spine order. See [section 5.4.2.3. The `page-list nav` Element](https://www.w3.org/publishing/epub32/epub-packages.html#sec-nav-pagelist):

> The page references within the `page-list` `nav` _MUST_ be ordered so that they match both the order of the targeted EPUB Content Documents in the spine and the order of each page within its respective EPUB Content Document.

In fact, this was originally reported by EPUBCheck as an error (following issue #888), but was then downgraded to a warning following a lengthly discussion in #1036, which is still an open issue in the EPUB Community Group as w3c/publ-epub-revision#1283).

There's probably not much we can do in EPUBCheck about that. If you'd like the rules to change, I'd advise you to contribute to the discussion in the community group. Meanwhile, your options are either to ignore this warning (it's "only" a warning after all) or to somehow make your page list and spine match the same order.

I'm closing this issue as `wontfix`, but feel free to keep on commenting here, and we could always reopen if the CG decides to change the spec or to further downgrade EPUBCheck's reporting!

**Closed** 2020-02-04 11:15 UTC
Labels: type: wontfix
