### ISSUE TITLE
4.2.5 error for multiple roles of an author or contributor?

### ISSUE THREAD

**Issue by Doktorchen** [w3c/epubcheck#1257] opened 2021-06-19 16:49 UTC
Version 4.2.5 claims:
"Error while parsing file: Property "role" cannot be declared more than once to refine a single "creator" or "contributor" property."

Where can I find this restriction in the 3.2 recommendation?
https://www.w3.org/publishing/epub32/epub-packages.html#sec-opf-dccreator
only says:
"The role property can be attached to the element to indicate the function the creator played in the creation of the content."

Often people have much more than one role.

If this is somehow related to triple-structures, of course, one needs another structure like a roles attribute to provide a (whitespace separated) list of roles with one meta element to one author or contributor element - or one has to refine the role value content to allow such lists explicitly.
MARC relator codes says: "The relator codes are three-character lowercase alphabetic strings that serve as identifiers." - no lists mentioned. 

Would be quite useless to put a huge amount of author/contributor elements including all related meta elements to refine such a person again and again for each role.
But this would be more relevant for a new recommendation, not for checking EBUB 3.2 books.

**Comment by mattgarrish** [comment] 2021-06-20 00:34
Closing as a duplicate of #1230

**Closed by mattgarrish** 2021-06-20 00:34 UTC
