### ISSUE TITLE
Possible incorrect role error reported on (inline) SVGs

### ISSUE THREAD

**Issue by ThomasR128** [w3c/epubcheck#1234] opened 2021-04-03 07:58 UTC
A purely decorative SVG (inline in this case) declared as
    `<svg xmlns="http://www.w3.org/2000/svg" role="presentation"> … </svg>`
is being reported as an error ("invalid role attribute, must be application, doc, or img").

The [SVG spec](https://www.w3.org/TR/SVG2/struct.html#roleattribute) says: _"The ‘role’ attribute must be a set of space-separated tokens having values defined in [Definition of Roles](https://www.w3.org/TR/wai-aria-1.1/#role_definitions) ([wai-aria], section 5.4)."_ `presentation` (and `none`) are allowed roles there, so I don't think this should be reported as an error.

**Comment by rdeltour** [comment] 2022-12-23 18:21
I could not reproduce the issue; it was probably fixed by an HTML schema update.

**Closed** 2022-12-23 18:22 UTC
Labels: type: unverified

**Comment by ThomasR128** [comment] 2022-12-23 20:19
Merry Christmas Romain.

I hope it’s not my lack of understanding being the real issue here.

The [SVG spec §5.13.2](https://www.w3.org/TR/SVG2/struct.html#roleattribute) and the [WAI-ARIA Graphics Module §4, 3](https://www.w3.org/TR/graphics-aria-1.0/#roles) _(‘Authors may mark elements for exclusion from the semantic representation of the document (the accessibility tree) by assigning the role [none](https://www.w3.org/TR/wai-aria-1.1/#none) or [presentation](https://www.w3.org/TR/wai-aria-1.1/#presentation).’)_ lead me to believe that `role="presentation"` is allowed on `svg` elements.

If I’m getting this wrong, and the role should be set not on the `svg` but instead on its parent or children (`g`, etc.), please correct me and disregard what follows.

Otherwise, here’s how to reproduce the issue:

Download the [Sous le vent](http://idpf.github.io/epub3-samples/30/samples.html#sous-le-vent) EPUB3 from the IDPF test suite and run epubcheck:
<img width="400" alt="Captura de Pantalla 2022-12-23 a las 19 51 17" src="https://user-images.githubusercontent.com/64253366/209395822-cca5fcd8-c8cb-4904-8a96-5cff7e9e4e5d.png">

Crack open the EPUB and open `pageNum-1.xthml`: 
<img width="400" alt="Captura de Pantalla 2022-12-23 a las 19 40 19" src="https://user-images.githubusercontent.com/64253366/209395847-772f5489-6a1d-4045-8376-25e4c02c8df5.png">

Add `role="presentation"` to the `svg` element (line 11):
<img width="400" alt="Captura de Pantalla 2022-12-23 a las 19 40 45" src="https://user-images.githubusercontent.com/64253366/209395870-48c21069-266a-4c68-a12b-8cf9c2288fae.png">

Run epubcheck again on a renamed copy. Note that epubcheck reports an error:
<img width="400" alt="Captura de Pantalla 2022-12-23 a las 19 53 27" src="https://user-images.githubusercontent.com/64253366/209395894-da640b44-1540-41a4-8bc6-e728ecd38138.png">

Modifying the role to `img` makes the error disappear again (as expected).

**Comment by mattgarrish** [comment] 2022-12-24 03:04
By the screen grabs, you're checking against 4.2.6. I tried this against the latest 5.0.0 beta and, like @rdeltour, don't get the error.

**Comment by ThomasR128** [comment] 2022-12-24 09:23
Solved in the beta? 👍

`<tongue in="cheek">`Your honour, guilty as charged of using the latest production-ready release instead of what’s labelled as ‘beta pre-release preview’.`</tongue>`
