### ISSUE TITLE
ePub 2 fixed layout issue

### ISSUE THREAD

**Issue by vigneshkumarelumalai** [w3c/epubcheck#679] opened 2016-03-03 06:51 UTC
Dear All,

Please suggest how to overcome the warning while validationg "WARNING:  CSS selector specifies absolute position." in ePub 2 fixed layout.

**Comment by tofi86** [comment] 2016-03-03 09:34
Did you close the issue on purpose?

**Comment by vigneshkumarintegra** [comment] 2016-03-03 09:35
yes

**Comment by vigneshkumarintegra** [comment] 2016-03-03 09:35
By mistake it happen

**Comment by ramygeorgemorcos** [comment] 2016-03-03 18:35
it 's sometimes validating your issues not always.Why?

**Comment by ramygeorgemorcos** [comment] 2016-03-03 18:36
[THE IMAGE AND SOUND IN THE DIGITAL INDUSTRY.docx](https://github.com/IDPF/epubcheck/files/157422/THE.IMAGE.AND.SOUND.IN.THE.DIGITAL.INDUSTRY.docx)

**Comment by mattgarrish** [comment] 2017-07-12 14:19
EPUB 2 doesn't define fixed layouts, so that's why the use of absolute positioning is discouraged.

But EPUB 2 only advised against it:

> Use of the CSS position property values to achieve absolute positioning (i.e. absolute and fixed) is strongly discouraged.

EPUB 3.0 made the use of fixed an error and EPUB 3.0.1 added absolute positioning as a warning.

So, technically, it shouldn't be a warning in EPUB 2 (maybe only an info message). 

And EPUB 3.1 returned mention of absolute/fixed positioning to authoring guidance instead of a "should".

**Comment by rdeltour** [comment] 2019-01-21 12:13
> And EPUB 3.1 returned mention of absolute/fixed positioning to authoring guidance instead of a "should not"/"must not".

These loosened rules have been maintained in EPUB 3.2 (see #899), so I suggest we tacked this issue in the `next/v4.2.0` branch.

Additionally, the checks come from the `ctc` package, which requires a major cleanup up in any case (unfortunately after the 4.2.0 milestone).

**Comment by rdeltour** [comment] 2019-01-21 12:14
Closing as duplicate of #899, as this will be fixed as a side effect.

**Closed by rdeltour** 2019-01-21 12:14 UTC
Labels: spec: EPUB 2.x, type: bug
