### ISSUE TITLE
Epub 2.0.1 validator error: "Error while parsing file: element "img" missing required attributes "alt" and "src"."

### ISSUE THREAD

**Issue by justin-b-918** [w3c/epubcheck#1332] opened 2022-04-24 20:31 UTC
I have tried six ways from Sunday to fix this.
Running through Calibre doesn't generate the same error.
Running through Sigil doesn't generator the error.
This is converted from a word .docx file with several images in the doc.

I have added alt text to the images withing Word so I wouldn't think the "alt" error would be an issue.
However the "src" error is beyond me. I know barely anything about epub file formats.

Any geniuses out there that can help an old man out?
![validator errors](https://user-images.githubusercontent.com/104325001/164995329-d495f807-97b1-488e-acfd-45d7f69c42b0.png)

**Comment by rdeltour** [comment] 2022-04-25 07:57
Somehow your Word to EPUB conversion tool generates `img` HTML elements that do not have `src` or `alt` attributes. The former attribute is used to point to the image file, the latter to give a textual description of the image. This is not valid HTML and is rejected by EPUBCheck.

Please note however that this issue tracker is reserved for reporting bugs or feature requests for EPUBCheck.
This is not a forum to ask for help or guidance on EPUB production.

I'm closing this issue as `invalid`, as this is apparently not a bug with EPUBCheck itself.

**Closed by rdeltour** 2022-04-25 07:57 UTC

**Comment by mattgarrish** [comment] 2022-04-25 11:18
> I'm closing this issue as `invalid`, as this is apparently not a bug with EPUBCheck itself.

Yes, I was wondering if it would report both as missing if only one was present, based on the original comment, but there are different messages depending on which are set.

To @justin-b-918, there's not much we can do here to help you. As @rdeltour says, the tool you're using to convert from Word is the likely culprit so you should see if there's a forum for help with it.

You may might also try exporting using the [DAISY WordToEPUB plugin](https://daisy.org/info-help/guidance-training/daisy-tools/getting-started-with-wordtoepub/), assuming that's not what you've used. It should handle exporting of images. If that is the tool you're using, there's a support email at the bottom of the page I linked to.
